image:
  registry: navneet78
  tag: local
  pullPolicy: IfNotPresent

replicas:
  dashboard: 1
  modelService: 1
  metricsService: 1

config:
  environmentName: Local
  appVersion: local
  octopusRelease: local
  refreshInterval: "8"
  defaultModel: supportpilot

service:
  dashboardPort: 80

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 300m
    memory: 256Mi

ingress:
  enabled: false
  className: traefik
  host: nexus.local
  path: /
